apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 8.1.2
  releaseName: argocd
  namespace: argocd
  valuesInline:
    configs:
      secret:
        argocdServerAdminPassword: $2a$10$l2JvLtIXRHdlFHPDQTjuBecLxv5y1wdGjliLYg/SZTcPaqOjRVsBC # admin/admin
      cm:
        url: https://localhost:8080
        users.anonymous.enabled: true
      rbac:
        policy.default: role:admin

    dex:
      enabled: false

    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: argocd-redis
        existingSecretPasswordKey: auth

    server:
      image:
        repository: argocd-overview-extension/argocd-server
        tag: latest
      containerSecurityContext: {}

patches:
- target:
    kind: Deployment
    name: argocd-server
  patch: |
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/6
    - op: remove
      path: /spec/template/spec/volumes/1
