---
name: 🚨 Lint Everything

on:
  merge_group: {}
  pull_request: {}

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk:
    name: ✅ Validate code quality
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: ⚡️ Run `trunk check`
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
