---
name: 📸 Chromatic Storybook

on:
  push:
    branches: [main]
    paths:
      - src/components/**
      - .storybook/**
      - package.json
      - pnpm-lock.yaml
  pull_request:
    paths:
      - src/components/**
      - .storybook/**
      - package.json
      - pnpm-lock.yaml

permissions: {}

jobs:
  chromatic:
    name: 📸 Chromatic Storybook
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: 📦 Install PNPM
        run: npm install -g pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📸 Run Chromatic
        uses: chromaui/action@bc2d84ad2b60813a67d995c5582d696104a19383 # v13.3.2
        with:
          exitOnceUploaded: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
