---
name: 🔒️ Security checks (Dependencies)

on:
  push:
    branches: [main]
    paths: [package.json, pnpm-lock.yaml]
  pull_request:
    paths: [package.json, pnpm-lock.yaml]
  schedule:
    - cron: 0 0 * * 1 # Run every Monday at midnight
  workflow_dispatch: {}

permissions: {}

jobs:
  security_audit:
    name: 🔍 Dependency security audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: 📦 Install PNPM
        run: npm install -g pnpm

      - name: 🔒 Install dependencies
        run: pnpm install

      - name: 🛡️ Run security audit
        run: pnpm audit --json | pnpx npm-audit-sarif /dev/stdin > pnpm-audit.sarif || true

      - name: 📊 Upload audit results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: pnpm-audit.sarif
          category: pnpm-audit
